### ISSUE TITLE
Refactoring Error & Success

### ISSUE THREAD

**Issue by Tebbee** [KarlMarx4701/In-Class-Behavior-Analyzer-Backend#4]
What is wrong: get_error_status, get_error_information, and get_success_status can all be moved to their own file. They are repeated throughout the program
How it can be fixed: Moving the three types of get requests to their own file or a file consisting of all of them
Where it is located at: Demographic_views, auth_views, etc
Folder, File, method, line number: 18-32 Demographic_views,  47-64 auth_views,
Who was the presenter: Ben
Who were the reviewers: Cody, Vanessa

**Comment by bklawson** [comment]
This is being closed as it has been fixed in the most recent version of the code.
